name: 'Review pull request'

# **What it does**: This script reviews if code trying to be merged passes all e2e and unit tests.
# **Why we have it**: We want to make sure that nothing it's at least broken.

on:
  pull_request:
    types: [ opened, edited, reopened ]

permissions:
  contents: read
  pull-requests: read

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install
        run: npm ci

      - name: Build and check types
        run: npm run build

      - name: Check unit tests
        run: npm run test:unit

      - name: Check e2e tests
        run: npm run test:e2e